name: GitHub CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-nugets:
    name: 🚀 Pack ${{matrix.projectName}}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        projectName: 
          - LanguageIdentification.CLD2
          - LanguageIdentification.CLD3
          - LanguageIdentification.FastText
          # - LanguageIdentification.Whatlang
          # - LanguageIdentification.MediaPipe
          # - LanguageIdentification.Lingua
          # - LanguageCode
    permissions:
      contents: read
      packages: write
    env:
      ROOT: ./src
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    steps:
    - uses: actions/checkout@v4
      with: 
        submodules: 'true'

    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - '${{env.ROOT}}/${{matrix.projectName}}/**'

    - uses: dorny/paths-filter@v3
      id: changes-native
      with:
        filters: |
          src:
            - '${{env.ROOT}}/${{matrix.projectName}}.Native/**'

    - name: 📂 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    - name: 🚀 Pack ${{matrix.projectName}}.Native
      if: steps.changes-native.outputs.src == 'true'
      working-directory: ${{env.ROOT}}/${{matrix.projectName}}.Native
      run: dotnet pack -c Release -o out 

    - name: 🚀 Pack ${{matrix.projectName}}
      if: steps.changes.outputs.src == 'true'
      working-directory: ${{env.ROOT}}/${{matrix.projectName}}
      run: dotnet pack -c Release -o out 

    - uses: actions/upload-artifact@v4
      if: steps.changes-native.outputs.src == 'true'
      with:
        name: build-${{matrix.projectName}}.Native
        path: ${{env.ROOT}}/${{matrix.projectName}}.Native/out
        retention-days: 1
        overwrite: 'true'
        compression-level: 0

    - uses: actions/upload-artifact@v4
      if: steps.changes.outputs.src == 'true'
      with:
        name: build-${{matrix.projectName}}
        path: ${{env.ROOT}}/${{matrix.projectName}}/out
        retention-days: 1
        overwrite: 'true'
        compression-level: 0

  test-nugets-linux:
    name: 🧪 Test on Linux
    runs-on: ubuntu-latest
    needs: build-nugets
    permissions:
      contents: read
      packages: write
    env:
      ROOT: ./src
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    steps:
    - uses: actions/checkout@v4
  
    - name: 📂 Files
      working-directory: ${{env.ROOT}}
      run: mkdir -p local-nugets

    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
        merge-multiple: true
        path: ${{env.ROOT}}/local-nugets

    - name: 📂 Files
      working-directory: ${{env.ROOT}}
      run: ls -R

    - name: 📂 Build Docker Image
      working-directory: ${{env.ROOT}}
      run: |
        docker build -f ./test.Dockerfile -t langunage-identification-test-runner:latest .
        docker build -f ./test-ci.Dockerfile -t langunage-identification-test-runner-ci:latest .

  test-nugets-windows:
    name: 🧪 Test on Windows
    runs-on: windows-latest
    needs: build-nugets
    permissions:
      contents: read
      packages: write
    env:
      ROOT: ./src
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    steps:
    - uses: actions/checkout@v4
  
    - name: 📂 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    - name: 📂 Files
      run: mkdir -p ${{env.ROOT}}/local-nugets

    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
        merge-multiple: true
        path: ${{env.ROOT}}/local-nugets

    - name: 📂 Files
      working-directory: ${{env.ROOT}}
      run: ls -R

    - name: 📂 Use local NuGet
      run: |
          $path = [System.IO.Path]::GetFullPath('${{env.ROOT}}/local-nugets')
          dotnet nuget add source $path

    - name: 🧪 Run Tests for LanguageIdentification
      working-directory: ${{env.ROOT}}/LanguageIdentification.Tests
      run: dotnet test -c CI

    - name: 🧪 Run Tests for LanguageCode
      working-directory: ${{env.ROOT}}/LanguageCode.Tests
      run: dotnet test -c CI

  test-nugets-macos:
    name: 🧪 Test on macOS
    runs-on: macos-latest
    needs: build-nugets
    permissions:
      contents: read
      packages: write
    env:
      ROOT: ./src
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}} 
    steps:
    - uses: actions/checkout@v4
  
    - name: 📂 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    - name: 📂 Files
      run: mkdir -p ${{env.ROOT}}/local-nugets

    - uses: actions/download-artifact@v4
      with:
        pattern: build-*
        merge-multiple: true
        path: ${{env.ROOT}}/local-nugets

    - name: 📂 Files
      working-directory: ${{env.ROOT}}
      run: ls -R

    - name: 📂 Use local NuGet
      run: |
          path=$(realpath "${{env.ROOT}}/local-nugets")
          dotnet nuget add source $path

    - name: 🧪 Run Tests for LanguageIdentification
      working-directory: ${{env.ROOT}}/LanguageIdentification.Tests
      run: dotnet test -c CI

    - name: 🧪 Run Tests for LanguageCode
      working-directory: ${{env.ROOT}}/LanguageCode.Tests
      run: dotnet test -c CI

  deploy-nugets:
    name: 🚚 Push ${{matrix.projectName}}
    runs-on: ubuntu-latest
    needs: 
      - test-nugets-linux
      - test-nugets-windows
      - test-nugets-macos
    if: github.ref == 'refs/heads/master'
    strategy:
      fail-fast: false
      matrix:
        projectName: 
          - LanguageIdentification.CLD2.Native
          - LanguageIdentification.CLD2
          - LanguageIdentification.CLD3.Native
          - LanguageIdentification.CLD3
          - LanguageIdentification.FastText.Native
          - LanguageIdentification.FastText
          - LanguageIdentification.Whatlang.Native
          - LanguageIdentification.Whatlang
          - LanguageIdentification.MediaPipe.Native
          - LanguageIdentification.MediaPipe
          - LanguageIdentification.Lingua.Native
          - LanguageIdentification.Lingua
          - LanguageCode
    permissions:
      contents: read
      packages: write
    env:
      ROOT: ./src
      NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      MICROSOFT_NUGET_AUTH_TOKEN: ${{ secrets.PACKAGES_WRITE_TOKEN }} 
    steps:
    - uses: actions/checkout@v4
  
    - uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          src:
            - '${{env.ROOT}}/${{matrix.projectName}}/**'

    - uses: actions/download-artifact@v4
      if: steps.changes.outputs.src == 'true'
      with:
        pattern: build-${{matrix.projectName}}
        path: ${{env.ROOT}}/${{matrix.projectName}}/out

    - name: 📂 Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          5.0.x
          6.0.x
          7.0.x
          8.0.x
        source-url: https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    - name: 📂 Files
      working-directory: ${{env.ROOT}}
      run: ls -R

    - name: 🚚 [GitHub] Push ${{matrix.projectName}} to registry
      if: steps.changes.outputs.src == 'true'
      working-directory: ${{env.ROOT}}/${{matrix.projectName}}
      run: |
        dotnet nuget push ./out/**/*.nupkg \
        --skip-duplicate -k ${{env.NUGET_AUTH_TOKEN}} \
        --source https://nuget.pkg.github.com/${{github.repository_owner}}/index.json

    - name: 🚚 [Microsoft] Push ${{matrix.projectName}} to registry
      if: steps.changes.outputs.src == 'true'
      working-directory: ${{env.ROOT}}/${{matrix.projectName}}
      run: |
        dotnet nuget push ./out/**/*.nupkg \
        --skip-duplicate -k ${{env.MICROSOFT_NUGET_AUTH_TOKEN}} \
        --source https://api.nuget.org/v3/index.json

    - uses: geekyeggo/delete-artifact@v5
      if: steps.changes.outputs.src == 'true'
      with:
        name: build-${{matrix.projectName}}
